iclab/centinel

centinel.py

daemonize import added, fixes #113

---

centinel/daemonize.py

Updated the cron commands and removed the old incompatible arguments.
@ben-jones: can you please review?

fixed daemonize script

---

centinel/backend.py

Fixed a bug where result submission always returned an error.
Added support for uploading uncompressed result files and compressed pcap files.
@ben-jones, will you do the honours?

Fixed result submission bugs

---

centinel/backend.py

better handling of HTTP 418 "consent not given" error, fixes #125

---

centinel/backend.py
centinel/client.py
centinel/data/country.txt
centinel/data/world.txt
centinel/experiment.py
centinel/experiments/baseline.py
centinel/primitives/dnslib.py
centinel/primitives/http.py
centinel/primitives/tls.py

This is the baseline URL testing experiment. It does HTTP GET, DNS, TLS cert get, and traceroute on mutiple lists of URLs while recording pcaps for each URL. It has been tested a few times and enhanced in order to take less time to finish and consume less disk space.
@ben-jones, can you please review this?

Baseline Experiments

---

README.md
centinel.py
centinel/__init__.py
centinel/backend.py
centinel/config.py
centinel/vpn/hma.py
setup.py
vpn.py

VPN client now sets its country before fetching the experiments (this wasn't done before and experiments were all US/global for all vantage points).
I have also fixed some bugs in the VPN client code as well as backend code.
@ben-jones, please review.

VPN improvement and minor bugfixes

---

centinel/backend.py
centinel/client.py
setup.py
vpn.py

Adding metadata (local timing data, scheduler name, info fetched from the server) to results for each experiment result file.
@ben-jones, please review.

Experiment metadata

---

centinel/backend.py

you can't change dictionaries as you iterate over them, which the
scheduler sync code did. I have updated it to fix the problem

fixed bug in scheduler updater

---

.gitignore
README.md
centinel/primitives/http.py

The urlparse library is already part of the default python library.
The new format of the http result is
- redirects (optional)
- request
- response
The response field is the last HTTP response that you are redirected to. Previous responses are stored in redirects

Added HTTP redirect support

---

centinel/cli.py

@ben-jones, please review (just a change of default filenames).

changed default binary location to centinel, fixes #156

---

centinel/__init__.py
setup.py

will now keep the version number in master, not dev, to minimize
distance between the branches

bumped version number in master

---

centinel/experiments/baseline.py
centinel/experiments/baseline_linear.py
centinel/vpn/cli.py
centinel/vpn/openvpn.py

Some vpn providers require using their own certificate, like IPVanish. In this pull request I added a new option for this. I also made some changes to vpn nodes config initialization.

Adding support of certificate in openvpn, plus minor bug fixes

---

centinel/primitives/traceroute.py
setup.py

Tested with different inputs, malformed inputs, etc. and it works. The output is better structured now.

Switching to trparse to parse traceroute output

---

centinel/__init__.py
centinel/primitives/traceroute.py
setup.py

@rnithyanand can you please review? This should be the final pull request for 1.5.4. Includes bugfixes and updates to the traceroute primitive.
It also fixes the parallel baseline issue where some threads ended prematurely.

Bugfixes for 1.5.4

---

centinel/cli.py
centinel/client.py
centinel/config.py
centinel/primitives/dnslib.py
centinel/primitives/http.py
centinel/primitives/tls.py
centinel/primitives/traceroute.py

This adds the `--verbose` (`-V`) flag to enable verbose logging. Also improves logging overall (e.g. better format, log to file) and adds some vebose log messages in various places.
@rnithyanand can you please review?

Verbose Logging

---

centinel/__init__.py
centinel/cli.py
centinel/daemonize.py
setup.py

This will allow users to choose the user that runs the daemonized experiments.

Schedule as current user

---

centinel/vpn/cli.py
centinel/vpn/openvpn.py

Added signal handler to disconnect VPN.
Added list of connected OpenVPN instances.
Check network connectivity and external IP before moving on to each endpoint.
Added some sleep time after VPN stopped

VPN walker reliability enhancement

---

centinel/primitives/dnslib.py

@rpanah can you review and merge this then release a new version?

inlcuded 8.8.8.8 in testing nameservers

---

centinel/cli.py
centinel/client.py
centinel/vpn/cli.py

@rpanah can you review and merge this?

Added VPN provider to metadata

---

centinel/client.py

@lianke123321 can you review please?

pcap bz2 failover (fixes #254), better memory management

---

centinel/primitives/http.py

This fixes the following issues:
* redirect requests are now embedded in the results (for some reason these were omitted)
* results are now properly parsed and searched for Location headers (this didn't work before due to case-sensitive search)
* Location header now takes precedence over meta redirect
* Empty host values from redirect URLs are now filled with the last host value

Debug and enhance HTTP primitive
